version: '2'
services:
  moodle:
    image: burcin/moodle
    links:
      - moodle_db
    environment:
       MOODLE_URL: "http://130.149.22.217:8080"
       DB_PORT_3306_TCP_ADDR: moodle_db
       DB_ENV_MYSQL_USER: moodle
       DB_ENV_MYSQL_PASSWORD: moodle
       DB_ENV_MYSQL_DATABASE: moodle
    ports:
      - "8080:80"
    restart: always
    volumes: 
      - .data/moodledata:/var/moodledata
      - .data/html/info.php:/var/www/html/info.php

  lb:
    image: dockercloud/haproxy
    links:
      - moodle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

  memcached:
   image: memcached
   ports:
    - "11211:11211"



  moodle_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    ports:
      - "3306:3306"
    volumes:
      - .data/moodledb:/var/lib/mysql
     
    restart: always

 

